<Project>
  <PropertyGroup>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <Authors>Phong Võ</Authors>
    <Company>ZeroUI</Company>
    <Copyright>Copyright © 2026 Phong Võ</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kzxl/ZeroUI</PackageProjectUrl>
    <RepositoryUrl>https://github.com/kzxl/ZeroUI.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Condition="Exists('README.md')">
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="Exists('README.md')">
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
