using System;
using System.Runtime.InteropServices;

namespace ZeroUI.Graphics.DirectX.Native
{
    public enum DXGI_FORMAT : uint
    {
        DXGI_FORMAT_UNKNOWN = 0,
        DXGI_FORMAT_R32G32B32A32_TYPELESS = 1,
        DXGI_FORMAT_R32G32B32A32_FLOAT = 2,
        DXGI_FORMAT_R32G32B32_FLOAT = 6,
        DXGI_FORMAT_R32G32_FLOAT = 16,
        DXGI_FORMAT_R8G8B8A8_UNORM = 28,
        DXGI_FORMAT_R8G8B8A8_UNORM_SRGB = 29,
        DXGI_FORMAT_B8G8R8A8_UNORM = 87,
        DXGI_FORMAT_B8G8R8A8_UNORM_SRGB = 91,
    }

    public enum DXGI_SWAP_EFFECT : uint
    {
        DXGI_SWAP_EFFECT_DISCARD = 0,
        DXGI_SWAP_EFFECT_SEQUENTIAL = 1,
        DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL = 3,
        DXGI_SWAP_EFFECT_FLIP_DISCARD = 4
    }

    [Flags]
    public enum DXGI_USAGE : uint
    {
        DXGI_USAGE_SHADER_INPUT = 1 << 4,
        DXGI_USAGE_RENDER_TARGET_OUTPUT = 1 << 5,
        DXGI_USAGE_BACK_BUFFER = 1 << 6,
        DXGI_USAGE_SHARED = 1 << 7,
        DXGI_USAGE_READ_ONLY = 1 << 8,
        DXGI_USAGE_DISCARD_ON_PRESENT = 1 << 9,
        DXGI_USAGE_UNORDERED_ACCESS = 1 << 10
    }

    [Flags]
    public enum DXGI_SWAP_CHAIN_FLAG : uint
    {
        DXGI_SWAP_CHAIN_FLAG_NONPREROTATED = 1,
        DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2,
        DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE = 4,
        DXGI_SWAP_CHAIN_FLAG_RESTRICTED_CONTENT = 8,
        DXGI_SWAP_CHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER = 16,
        DXGI_SWAP_CHAIN_FLAG_DISPLAY_ONLY = 32,
        DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT = 64,
        DXGI_SWAP_CHAIN_FLAG_FOREGROUND_LAYER = 128,
        DXGI_SWAP_CHAIN_FLAG_FULLSCREEN_VIDEO = 256,
        DXGI_SWAP_CHAIN_FLAG_HW_PROTECTED = 512,
        DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING = 2048,
    }

    [Flags]
    public enum DXGI_ADAPTER_FLAG : uint
    {
        DXGI_ADAPTER_FLAG_NONE = 0,
        DXGI_ADAPTER_FLAG_REMOTE = 1,
        DXGI_ADAPTER_FLAG_SOFTWARE = 2
    }
}
