<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <RootNamespace>ZeroUI.Wpf</RootNamespace>
    <AssemblyName>ZeroUI.Wpf</AssemblyName>
    <Description>Ultra-high-performance WPF industrial UI suite with zero-allocation virtual big data grid and modern reactive theme engine.</Description>
    <PackageTags>wpf;datagrid;grid;scada;hmi;industrial-automation;virtualization;zero-allocation;dark-theme</PackageTags>
    <Authors>Phong Võ</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kzxl/ZeroUI</PackageProjectUrl>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeroUI.Core\ZeroUI.Core.csproj" />
  </ItemGroup>
</Project>
